# Generated by Django 4.2.26 on 2026-01-08 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales_billing', '0002_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
