# Generated by Django 4.2.26 on 2026-01-08 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_billing', '0003_expenditure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwaka', models.CharField(help_text="Year range e.g. '2016 - 2018'", max_length=50)),
                ('mwezi', models.CharField(help_text="Month range e.g. 'Feb. 2016 - Dec. 2022'", max_length=100)),
                ('units_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Report Entry',
                'verbose_name_plural': 'Custom Report Entries',
                'ordering': ['created_at'],
            },
        ),
    ]
