# Generated by Django 4.2.26 on 2026-01-09 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('units_produced', models.DecimalField(decimal_places=2, default=0, help_text='Units produced on this day', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about production', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Water Production',
                'verbose_name_plural': 'Water Productions',
                'ordering': ['-date'],
            },
        ),
    ]
