# Generated by Django 4.2.26 on 2026-01-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.DecimalField(decimal_places=2, help_text='Number of units (e.g., liters)', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (unit * price)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
